### ISSUE TITLE
Setting the destination for fault-injection

### ISSUE THREAD

**Issue by abdul-manaan** [chaostoolkit-incubator/chaostoolkit-istio#12]
Currently, you guys assume that the destination will have a host and a subset. However, this will not always be the case. For instance, there can be a destination like this:
```
route:
    - destination:
        host: web.robot-shop.svc.cluster.local
        port:
          number: 8080
```

In that case, the function add_delay_fault or remove_delay_fault are not going to work. Because you guys assume subset field will always be there. 
I am referring to chaostoolkit-istio pip package. I am using Python3.5 and have downloaded the chaostoolkit-istio 0.1.4
